services:
  app:
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: database.sqlite
      DB_HOST:
      DB_PORT:
      DB_USERNAME:
      DB_PASSWORD:
    volumes:
      - spent_sqlite:/var/www/html/database

volumes:
  spent_sqlite:
